INSERT INTO departments (department)
VALUES
('kitchen')
('bartender')
('server')
('management')

INSERT INTO roles (title, hourly, department_id)
VALUES
('line cook', 10.00, 1)
('chef', 12.00, 1)
('am bartender', 7.25, 2)
('pm bartender', 7.25, 2)
('swing bartender', 7.25, 2)
('am server', 2.13, 3)
('pm server', 2.13, 3)
('general manager', 'Salary', 4)
('operations manager', 'Salary', 4)
('kitchen manager', 15.00, 4)

INSERT INTO employees (first_name, last_name, role_id)
('John', 'Locke')
('Sayid', 'Jarrah')
('Jack', 'Shepherd')
('Kate', 'Austen')
('Boone', 'Carlyle')
('Shannon', 'Rutherford')
('Ana Lucia', 'Cortez')
('Mister', 'Eko')
('Desmond', 'Hume')