INSERT INTO departments (department)
VALUES
('kitchen')
('bartender')
('server')
('management')

INSERT INTO roles (title, hourly, department_id)
VALUES
('line cook')
('chef')
('am bartender')
('pm bartender')
('swing bartender')
('am server')
('pm server')
('general manager')
('operations manager')
('kitchen manager')

INSERT INTO employees (first_name, last_name, role_id, manager_id)
('John', 'Locke')
('Sayid', 'Jarrah')
('Jack', 'Shepherd')
('Kate', 'Austen')
('Boone', 'Carlyle')
('Shannon', 'Rutherford')
('Ana Lucia', 'Cortez')
('Mister', 'Eko')
('Desmond', 'Hume')